from CWTree import CWTree

if __name__ == "__main__":
    morse = CWTree()
    print("A Test: ")
    morse.traverse(morse.LEFT)
    morse.traverse(morse.RIGHT)
    morse.flush()
    print("")

    print("B Test: ")
    morse.traverse(morse.RIGHT)
    morse.traverse(morse.LEFT)
    morse.traverse(morse.LEFT)
    morse.traverse(morse.LEFT)
    morse.flush()
    print("")

    print("C Test: ")
    morse.traverse(morse.RIGHT)
    morse.traverse(morse.LEFT)
    morse.traverse(morse.RIGHT)
    morse.traverse(morse.LEFT)
    morse.flush()
    print("")

    print("D Test: ")
    morse.traverse(morse.RIGHT)
    morse.traverse(morse.LEFT)
    morse.traverse(morse.LEFT)
    morse.flush()
    print("")

    print("E Test: ")
    morse.traverse(morse.LEFT)
    morse.flush()
    print("")

    print("F Test: ")
    morse.traverse(morse.LEFT)
    morse.traverse(morse.LEFT)
    morse.traverse(morse.RIGHT)
    morse.traverse(morse.LEFT)
    morse.flush()
    print("")

    print("G Test: ")
    morse.traverse(morse.RIGHT)
    morse.traverse(morse.RIGHT)
    morse.traverse(morse.LEFT)
    morse.flush()
    print("")

    print("H Test: ")
    morse.traverse(morse.LEFT)
    morse.traverse(morse.LEFT)
    morse.traverse(morse.LEFT)
    morse.traverse(morse.LEFT)
    morse.flush()
    print("")

    print("I Test: ")
    morse.traverse(morse.LEFT)
    morse.traverse(morse.LEFT)
    morse.flush()
    print("")

    print("J Test: ")
    morse.traverse(morse.LEFT)
    morse.traverse(morse.RIGHT)
    morse.traverse(morse.RIGHT)
    morse.traverse(morse.RIGHT)
    morse.flush()
    print("")

    print("K Test: ")
    morse.traverse(morse.RIGHT)
    morse.traverse(morse.LEFT)
    morse.traverse(morse.RIGHT)
    morse.flush()
    print("")

    print("L Test: ")
    morse.traverse(morse.LEFT)
    morse.traverse(morse.RIGHT)
    morse.traverse(morse.LEFT)
    morse.traverse(morse.LEFT)
    morse.flush()
    print("")

    print("M Test: ")
    morse.traverse(morse.RIGHT)
    morse.traverse(morse.RIGHT)
    morse.flush()
    print("")

    print("N Test: ")
    morse.traverse(morse.RIGHT)
    morse.traverse(morse.LEFT)
    morse.flush()
    print("")

    print("O Test: ")
    morse.traverse(morse.RIGHT)
    morse.traverse(morse.RIGHT)
    morse.traverse(morse.RIGHT)
    morse.flush()
    print("")

    print("P Test: ")
    morse.traverse(morse.LEFT)
    morse.traverse(morse.RIGHT)
    morse.traverse(morse.RIGHT)
    morse.traverse(morse.LEFT)
    morse.flush()
    print("")

    print("Q Test: ")
    morse.traverse(morse.RIGHT)
    morse.traverse(morse.RIGHT)
    morse.traverse(morse.LEFT)
    morse.traverse(morse.RIGHT)
    morse.flush()
    print("")

    print("R Test: ")
    morse.traverse(morse.LEFT)
    morse.traverse(morse.RIGHT)
    morse.traverse(morse.LEFT)
    morse.flush()
    print("")

    print("S Test: ")
    morse.traverse(morse.LEFT)
    morse.traverse(morse.LEFT)
    morse.traverse(morse.LEFT)
    morse.flush()
    print("")

    print("T Test: ")
    morse.traverse(morse.RIGHT)
    morse.flush()
    print("")

    print("U Test: ")
    morse.traverse(morse.LEFT)
    morse.traverse(morse.LEFT)
    morse.traverse(morse.RIGHT)
    morse.flush()
    print("")

    print("V Test: ")
    morse.traverse(morse.LEFT)
    morse.traverse(morse.LEFT)
    morse.traverse(morse.LEFT)
    morse.traverse(morse.RIGHT)
    morse.flush()
    print("")

    print("W Test: ")
    morse.traverse(morse.LEFT)
    morse.traverse(morse.RIGHT)
    morse.traverse(morse.RIGHT)
    morse.flush()
    print("")

    print("X Test: ")
    morse.traverse(morse.RIGHT)
    morse.traverse(morse.LEFT)
    morse.traverse(morse.LEFT)
    morse.traverse(morse.RIGHT)
    morse.flush()
    print("")

    print("Y Test: ")
    morse.traverse(morse.RIGHT)
    morse.traverse(morse.LEFT)
    morse.traverse(morse.RIGHT)
    morse.traverse(morse.RIGHT)
    morse.flush()
    print("")

    print("Z Test: ")
    morse.traverse(morse.RIGHT)
    morse.traverse(morse.RIGHT)
    morse.traverse(morse.LEFT)
    morse.traverse(morse.LEFT)
    morse.flush()
    print("")

    print("1 Test: ")
    morse.traverse(morse.LEFT)
    morse.traverse(morse.RIGHT)
    morse.traverse(morse.RIGHT)
    morse.traverse(morse.RIGHT)
    morse.traverse(morse.RIGHT)
    morse.flush()
    print("")

    print("2 Test: ")
    morse.traverse(morse.LEFT)
    morse.traverse(morse.LEFT)
    morse.traverse(morse.RIGHT)
    morse.traverse(morse.RIGHT)
    morse.traverse(morse.RIGHT)
    morse.flush()
    print("")

    print("3 Test: ")
    morse.traverse(morse.LEFT)
    morse.traverse(morse.LEFT)
    morse.traverse(morse.LEFT)
    morse.traverse(morse.RIGHT)
    morse.traverse(morse.RIGHT)
    morse.flush()
    print("")

    print("4 Test: ")
    morse.traverse(morse.LEFT)
    morse.traverse(morse.LEFT)
    morse.traverse(morse.LEFT)
    morse.traverse(morse.LEFT)
    morse.traverse(morse.RIGHT)
    morse.flush()
    print("")

    print("5 Test: ")
    morse.traverse(morse.LEFT)
    morse.traverse(morse.LEFT)
    morse.traverse(morse.LEFT)
    morse.traverse(morse.LEFT)
    morse.traverse(morse.LEFT)
    morse.flush()
    print("")

    print("6 Test: ")
    morse.traverse(morse.RIGHT)
    morse.traverse(morse.LEFT)
    morse.traverse(morse.LEFT)
    morse.traverse(morse.LEFT)
    morse.traverse(morse.LEFT)
    morse.flush()
    print("")

    print("7 Test: ")
    morse.traverse(morse.RIGHT)
    morse.traverse(morse.RIGHT)
    morse.traverse(morse.LEFT)
    morse.traverse(morse.LEFT)
    morse.traverse(morse.LEFT)
    morse.flush()
    print("")

    print("8 Test: ")
    morse.traverse(morse.RIGHT)
    morse.traverse(morse.RIGHT)
    morse.traverse(morse.RIGHT)
    morse.traverse(morse.LEFT)
    morse.traverse(morse.LEFT)
    morse.flush()
    print("")

    print("9 Test: ")
    morse.traverse(morse.RIGHT)
    morse.traverse(morse.RIGHT)
    morse.traverse(morse.RIGHT)
    morse.traverse(morse.RIGHT)
    morse.traverse(morse.LEFT)
    morse.flush()
    print("")

    print("0 Test: ")
    morse.traverse(morse.RIGHT)
    morse.traverse(morse.RIGHT)
    morse.traverse(morse.RIGHT)
    morse.traverse(morse.RIGHT)
    morse.traverse(morse.RIGHT)
    morse.flush()
    print("")

    print("+ Test: ")
    morse.traverse(morse.LEFT)
    morse.traverse(morse.RIGHT)
    morse.traverse(morse.LEFT)
    morse.traverse(morse.RIGHT)
    morse.traverse(morse.LEFT)
    morse.flush()
    print("")

    print("/ Test: ")
    morse.traverse(morse.RIGHT)
    morse.traverse(morse.LEFT)
    morse.traverse(morse.LEFT)
    morse.traverse(morse.RIGHT)
    morse.traverse(morse.LEFT)
    morse.flush()
    print("")

    print("= Test: ")
    morse.traverse(morse.RIGHT)
    morse.traverse(morse.LEFT)
    morse.traverse(morse.LEFT)
    morse.traverse(morse.LEFT)
    morse.traverse(morse.RIGHT)
    morse.flush()
    print("")